services:
  react-app:
    image: docker-react-app
    stdin_open: true
    build: ./react-app
    ports:
      - "3000:3000"
    networks:
      - mern-globalthinktec
  api-server:
    image: docker-api-server
    restart: always
    build: ./api-server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mern-globalthinktec
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/globalthinktec
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH: false
      PORT: 5000
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mern-globalthinktec
    volumes:
      - ./api-server/src/connections/init-mongo-db-collections.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: globalthinktec
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
networks:
  mern-globalthinktec:
    driver: bridge
