version: "3"
services:
  react-app:
    image: docker-react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-globalthinktec
  api-server:
    image: docker-api-server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mern-globalthinktec
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-globalthinktec
    volumes:
      - mongo-data:/data/db
networks:
  mern-globalthinktec:
    driver: bridge
volumes:
  mongo-data:
    driver: local